/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScorerRouteImport } from './routes/scorer'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as NoterRouteImport } from './routes/noter'
import { Route as FixerRouteImport } from './routes/fixer'
import { Route as DropperRouteImport } from './routes/dropper'
import { Route as IndexRouteImport } from './routes/index'

const ScorerRoute = ScorerRouteImport.update({
  id: '/scorer',
  path: '/scorer',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const NoterRoute = NoterRouteImport.update({
  id: '/noter',
  path: '/noter',
  getParentRoute: () => rootRouteImport,
} as any)
const FixerRoute = FixerRouteImport.update({
  id: '/fixer',
  path: '/fixer',
  getParentRoute: () => rootRouteImport,
} as any)
const DropperRoute = DropperRouteImport.update({
  id: '/dropper',
  path: '/dropper',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dropper': typeof DropperRoute
  '/fixer': typeof FixerRoute
  '/noter': typeof NoterRoute
  '/redirect': typeof RedirectRoute
  '/scorer': typeof ScorerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dropper': typeof DropperRoute
  '/fixer': typeof FixerRoute
  '/noter': typeof NoterRoute
  '/redirect': typeof RedirectRoute
  '/scorer': typeof ScorerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dropper': typeof DropperRoute
  '/fixer': typeof FixerRoute
  '/noter': typeof NoterRoute
  '/redirect': typeof RedirectRoute
  '/scorer': typeof ScorerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dropper' | '/fixer' | '/noter' | '/redirect' | '/scorer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dropper' | '/fixer' | '/noter' | '/redirect' | '/scorer'
  id:
    | '__root__'
    | '/'
    | '/dropper'
    | '/fixer'
    | '/noter'
    | '/redirect'
    | '/scorer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DropperRoute: typeof DropperRoute
  FixerRoute: typeof FixerRoute
  NoterRoute: typeof NoterRoute
  RedirectRoute: typeof RedirectRoute
  ScorerRoute: typeof ScorerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scorer': {
      id: '/scorer'
      path: '/scorer'
      fullPath: '/scorer'
      preLoaderRoute: typeof ScorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noter': {
      id: '/noter'
      path: '/noter'
      fullPath: '/noter'
      preLoaderRoute: typeof NoterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixer': {
      id: '/fixer'
      path: '/fixer'
      fullPath: '/fixer'
      preLoaderRoute: typeof FixerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropper': {
      id: '/dropper'
      path: '/dropper'
      fullPath: '/dropper'
      preLoaderRoute: typeof DropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DropperRoute: DropperRoute,
  FixerRoute: FixerRoute,
  NoterRoute: NoterRoute,
  RedirectRoute: RedirectRoute,
  ScorerRoute: ScorerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
